[general]
import = ["~/.config/alacritty/local.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# size = 10.5

[window]
dimensions = { columns = 160, lines = 40 }
position = { x = 400, y = 250 }

title = "👽"
dynamic_title = false
decorations_theme_variant = "Dark"

[env]
# -- vim/neovim + tmux fix, second, begin --
# https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
# https://stackoverflow.com/a/41786092/571465
# https://stackoverflow.com/a/55616731/571465
# https://stackoverflow.com/a/58842892/571465
TERM = "xterm-256color"
# TERM = "screen-256color"
# -- vim/neovim + tmux fix, second, end --
